config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "movies#index"
  # Routes for the Movie resource:
  # CREATE
  get "/movies/new", :controller => "movies", :action => "new"
  post "/create_movie", :controller => "movies", :action => "create"

  # READ
  get "/movies", :controller => "movies", :action => "index"
  get "/movies/:id", :controller => "movies", :action => "show"

  # UPDATE
  get "/movies/:id/edit", :controller => "movies", :action => "edit"
  post "/update_movie/:id", :controller => "movies", :action => "update"

  # DELETE
  get "/delete_movie/:id", :controller => "movies", :action => "destroy"
  #------------------------------

  devise_for :directors
  # Routes for the Director resource:
  # READ
  get "/directors", :controller => "directors", :action => "index"
  get "/directors/:id", :controller => "directors", :action => "show"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  before_save :geocode_address

  def geocode_address
    if self.address.present?
      url = "http://maps.googleapis.com/maps/api/geocode/json?address=#{URI.encode(self.address)}"

      raw_data = open(url).read

      parsed_data = JSON.parse(raw_data)

      if parsed_data["results"].present?
        self.address_latitude = parsed_data["results"][0]["geometry"]["location"]["lat"]

        self.address_longitude = parsed_data["results"][0]["geometry"]["location"]["lng"]

        self.address_formatted_address = parsed_data["results"][0]["formatted_address"]
      end
    end
  end
  mount_uploader :image, ImageUploader

  # Direct associations

  has_many   :movies,
             :dependent => :destroy

  # Indirect associations

  # Validations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/movie.rb
class Movie < ApplicationRecord
  # Direct associations

  belongs_to :director

  # Indirect associations

  # Validations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_director!

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, :keys => [:name, :dob, :age, :bio, :oscar, :image, :address, :show_time])

    devise_parameter_sanitizer.permit(:account_update, :keys => [:name, :dob, :age, :bio, :oscar, :image, :address, :show_time])
  end
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.page(params[:page]).per(10)
    @location_hash = Gmaps4rails.build_markers(@directors.where.not(:address_latitude => nil)) do |director, marker|
      marker.lat director.address_latitude
      marker.lng director.address_longitude
      marker.infowindow "<h5><a href='/directors/#{director.id}'>#{director.created_at}</a></h5><small>#{director.address_formatted_address}</small>"
    end
  end

  def show
    @director = Director.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @q = Movie.ransack(params[:q])
    @movies = @q.result(:distinct => true).includes(:director).page(params[:page]).per(10)

    render("movies/index.html.erb")
  end

  def show
    @movie = Movie.find(params[:id])

    render("movies/show.html.erb")
  end

  def new
    @movie = Movie.new

    render("movies/new.html.erb")
  end

  def create
    @movie = Movie.new

    @movie.title = params[:title]
    @movie.duration = params[:duration]
    @movie.rating = params[:rating]
    @movie.description = params[:description]
    @movie.director_id = params[:director_id]

    save_status = @movie.save

    if save_status == true
      redirect_to(:back, :notice => "Movie created successfully.")
    else
      render("movies/new.html.erb")
    end
  end

  def edit
    @movie = Movie.find(params[:id])

    render("movies/edit.html.erb")
  end

  def update
    @movie = Movie.find(params[:id])

    @movie.title = params[:title]
    @movie.duration = params[:duration]
    @movie.rating = params[:rating]
    @movie.description = params[:description]
    @movie.director_id = params[:director_id]

    save_status = @movie.save

    if save_status == true
      redirect_to(:back, :notice => "Movie updated successfully.")
    else
      render("movies/edit.html.erb")
    end
  end

  def destroy
    @movie = Movie.find(params[:id])

    @movie.destroy

    if URI(request.referer).path == "/movies/#{@movie.id}"
      redirect_to("/", :notice => "Movie deleted.")
    else
      redirect_to(:back, :notice => "Movie deleted.")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directors/index.html.erb
<div class="page-header">
  <h1>
    Directors
    <a href="/directors/new" class="btn btn-lg btn-success">New Director</a>
  </h1>
</div>


<div class="row m-b-2">
  <div class="col-md-12">
    <div>
      <div id="location_map" style="height: 480px;"></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <tr>
        <th>Name</th>
        <th>Dob</th>
        <th>Age</th>
        <th>Bio</th>
        <th>Oscar</th>
        <th>Image</th>
        <th>Address</th>
        <th>Show time</th>
        <th>Actions</th>
      </tr>

      <% @directors.each do |director| %>
      <tr>
        <td><%= director.name %></td>
        <td><%= director.dob %></td>
        <td><%= director.age %></td>
        <td><%= director.bio %></td>
        <td><%= director.oscar %></td>
        <td><img src='<%= director.image %>' class='img-responsive'></td>
        <td><%= director.address %></td>
        <td><%= director.show_time %></td>
        <td>
          <a href="/directors/<%= director.id %>" class="btn btn-primary">Show</a>
        </td>
      </tr>
      <% end %>
    </table>
    <%= paginate @directors, theme: 'twitter-bootstrap-4' %>
  </div>
</div>

<script src="//maps.google.com/maps/api/js?v=3.24&key=AIzaSyCOTPWiuvyyo6sKoIBzKA4-1ol-vTOIOlM"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'location_map'}}, function(){
    markers = handler.addMarkers(<%= raw @location_hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/directors/show.html.erb
<div class="page-header">
  <h3>Director #<%= @director.id %></h3>
</div>

<div class="row">
  <div class="col-md-12 mb-2">
    <dl class="dl-horizontal">
      <dt>Name</dt>
      <dd><%= @director.name %></dd>

      <dt>Dob</dt>
      <dd><%= @director.dob %></dd>

      <dt>Age</dt>
      <dd><%= @director.age %></dd>

      <dt>Bio</dt>
      <dd><%= @director.bio %></dd>

      <dt>Oscar</dt>
      <dd><%= @director.oscar %></dd>

      <dt>Image</dt>
      <dd><img src="<%= @director.image %>" class="img-responsive"></dd>

      <dt>Address</dt>
      <dd>
        <div>
          <div id="location_map" style="height: 480px;"></div>
        </div>
      </dd>

      <dt>Show time</dt>
      <dd><%= @director.show_time %></dd>

    </dl>

    <div class="btn-group btn-group-justified">
      <a href="/directors" class="btn btn-primary">
        Back
      </a>
    </div>
  </div>
</div>

<!-- A Director has many movies -->

<div class="row">
  <div class="col-md-12">
    <ul class="list-group">
      <li class="list-group-item list-group-item-info">
        Movies
      </li>

      <% @director.movies.each do |movie| %>
        <li class="list-group-item">
          <a href="/movies/<%= movie.id %>">
            <%= movie.created_at %>
          </a>
          <div class="btn-group btn-group-xs pull-right">
            <a href="/movies/<%= movie.id %>" class="btn btn-primary">
              <i class="fa fa-search-plus"></i>
            </a>
            <a href="/movies/<%= movie.id %>/edit" class="btn btn-warning">
              <i class="fa fa-edit"></i>
            </a>
            <a href="/delete_movie/<%= movie.id %>" class="btn btn-danger" rel="nofollow">
              <i class="fa fa-trash-o"></i>
            </a>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>


<script src="//maps.google.com/maps/api/js?v=3.24&key=AIzaSyCOTPWiuvyyo6sKoIBzKA4-1ol-vTOIOlM"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'location_map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= @director.address_latitude %>,
        "lng": <%= @director.address_longitude %>,
        "infowindow": "<h5><%= @director.created_at %></h5><small><%= @director.address_formatted_address %></small>"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>RansackDebugIssueNew</title>


  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 60px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">RansackDebugIssueNew</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/movies">Movies</a></li>
          <li><a href="/directors">Directors</a></li>
          <li><a href="/rails/info">Sitemap</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_director.present? %>
            <li>
              <a href="/directors/edit">
                <%= current_director.name %>
              </a>
            </li>

            <li>
              <a href="/directors/sign_out" data-method="delete" rel="nofollow">
                Sign Out
              </a>
            </li>
          <% else %>
            <li>
              <a href="/directors/sign_up">
                Sign Up
              </a>
            </li>

            <li>
              <a href="/directors/sign_in">
                Sign In
              </a>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/movies/edit.html.erb
<!-- Validation failure messages -->
<% if @movie.errors.any? %>
  <% @movie.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<div class="page-header">
  <h3>Edit Movie #<%= @movie.id %></h3>
</div>

<div class="row">
  <div class="col-md-12">
    <form action="/update_movie/<%= @movie.id %>" method="post">
      <!-- Hidden input for authenticity token to protect from forgery -->
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

      <!-- Label and input for title -->
      <div class="form-group">
        <label for="title" class="control-label">
          Title
        </label>

        <input type="text" id="title" name="title" placeholder="Title" class="form-control" value="<%= @movie.title %>">
      </div>

      <!-- Label and input for duration -->
      <div class="form-group">
        <label for="duration" class="control-label">
          Duration
        </label>

        <input type="text" id="duration" name="duration" placeholder="Duration" class="form-control" value="<%= @movie.duration %>">
      </div>

      <!-- Label and input for rating -->
      <div class="form-group">
        <label for="rating" class="control-label">
          Rating
        </label>

        <input type="text" id="rating" name="rating" placeholder="Rating" class="form-control" value="<%= @movie.rating %>">
      </div>

      <!-- Label and input for description -->
      <div class="form-group">
        <label for="description" class="control-label">
          Description
        </label>

        <textarea id="description" name="description" placeholder="Description" class="form-control" rows="3"><%= @movie.description %></textarea>
      </div>

      <!-- Label and input for director_id -->
      <div class="form-group">
        <label for="director_id" class="control-label">
          Director
        </label>

        <%= select_tag(:director_id, options_from_collection_for_select(Director.all, :id, :name, @movie.director_id), :class => "form-control") %>
      </div>

      <button class="btn btn-warning">
        Update Movie
      </button>
      or
      <a href="/movies/<%= @movie.id %>">Cancel</a>
    </form>
  </div>
</div>

app/views/movies/index.html.erb
<div class="page-header">
  <h1>
    Movies
    <a href="/movies/new" class="btn btn-lg btn-success">New Movie</a>
  </h1>
</div><div class="row mb-1">
  <div class="col-md-12">
    <%= search_form_for @q, :class => "collapse", :id => "movies_filters" do |f| %>
      <p class="lead">Narrow results:</p>

        <div class="form-group">
    <%= f.label :description_cont, "Description contains" %>
    <%= f.text_field :description_cont, :class => "form-control", :placeholder => "Description contains" %>
  </div>

<div class="form-group">
    <%= f.label :rating_gteq, "Rating greater than or equal to" %>
    <%= f.text_field :rating_gteq, :class => "form-control", :placeholder => "Rating greater than or equal to" %>
  </div>

<div class="form-group">
    <%= f.label :rating_lteq, "Rating less than or equal to" %>
    <%= f.text_field :rating_lteq, :class => "form-control", :placeholder => "Rating less than or equal to" %>
  </div>

<div class="form-group">
    <%= f.label :duration_gteq, "Duration greater than or equal to" %>
    <%= f.text_field :duration_gteq, :class => "form-control", :placeholder => "Duration greater than or equal to" %>
  </div>

<div class="form-group">
    <%= f.label :duration_lteq, "Duration less than or equal to" %>
    <%= f.text_field :duration_lteq, :class => "form-control", :placeholder => "Duration less than or equal to" %>
  </div>

<div class="form-group">
    <%= f.label :title_cont, "Title contains" %>
    <%= f.text_field :title_cont, :class => "form-control", :placeholder => "Title contains" %>
  </div>

<div class="form-group">
      <%= f.label :created_at, "Created at" %>
    </div>
      <div class="form-group">
          <div class="row">
            <div class='col-md-6'>
              <div class='input-group date' id='created_atgteqPicker'>
                  <%= f.text_field :created_at_gteq, :class => "form-control", :placeholder => "Created at greater than or equal to" %>
                  <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                  </span>
              </div>
            </div>

            <div class='col-md-6'>
              <div class='input-group date' id='created_atlteqPicker'>
                  <%= f.text_field :created_at_lteq, :class => "form-control", :placeholder => "Created at less than or equal to" %>
                  <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                  </span>
              </div>
            </div>
          </div>
      </div>
      <script type="text/javascript">
          $(function () {
              $('#created_atgteqPicker').datetimepicker({
                  format: 'YYYY-MM-DD hh:mm:ss'
              });
              $('#created_atlteqPicker').datetimepicker({
                  useCurrent: false,
                  format: 'YYYY-MM-DD hh:mm:ss'
              });
              $('#created_atgteqPicker').on("dp.change", function (e) {
                  $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
              });
              $('#created_atlteqPicker').on("dp.change", function (e) {
                  $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
              });
          });
      </script>

        <div class="form-group">
      <%= f.label :director_name_cont, "Director name contains" %>
      <%= f.text_field :director_name_cont, :class => "form-control", :placeholder => "Director name contains" %>
    </div>

      <%= f.submit :class => "btn btn-primary btn-block" %>

      <a href="/movies" class="btn btn-default btn-block">Clear filters</a>
    <% end %>
    <a class="btn btn-default btn-block mb-1" data-toggle="collapse" href="#movies_filters">
      Show Filters
    </a>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <tr>
        <th>Title</th>
        <th>Duration</th>
        <th>Rating</th>
        <th>Description</th>
        <th>Director</th>
        <th>Actions</th>
      </tr>

      <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.duration %></td>
        <td><%= movie.rating %></td>
        <td><%= movie.description %></td>
        <td>
          <% if movie.director.present? %>
            <a href="/directors/<%= movie.director.id %>">
              <%= movie.director.name %>
            </a>
          <% end %>
        </td>
        <td>
          <a href="/movies/<%= movie.id %>" class="btn btn-primary">Show</a>
          <a href="/movies/<%= movie.id %>/edit" class="btn btn-warning">Edit</a>
          <a href="/delete_movie/<%= movie.id %>" class="btn btn-danger" rel="nofollow">Delete</a>
        </td>
      </tr>
      <% end %>
    </table>
    <%= paginate @movies, theme: 'twitter-bootstrap-4' %>
  </div>
</div>

app/views/movies/new.html.erb
<!-- Validation failure messages -->
<% if @movie.errors.any? %>
  <% @movie.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<div class="page-header">
  <h3>Add Movie</h3>
</div>

<div class="row">
  <div class="col-md-12">
    <form action="/create_movie" method="post">
      <!-- Hidden input for authenticity token to protect from forgery -->
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

      <!-- Label and input for title -->
      <div class="form-group">
        <label for="title" class="control-label">
          Title
        </label>

        <input type="text" id="title" name="title" placeholder="Title" class="form-control" value="<%= @movie.title %>">
      </div>

      <!-- Label and input for duration -->
      <div class="form-group">
        <label for="duration" class="control-label">
          Duration
        </label>

        <input type="text" id="duration" name="duration" placeholder="Duration" class="form-control" value="<%= @movie.duration %>">
      </div>

      <!-- Label and input for rating -->
      <div class="form-group">
        <label for="rating" class="control-label">
          Rating
        </label>

        <input type="text" id="rating" name="rating" placeholder="Rating" class="form-control" value="<%= @movie.rating %>">
      </div>

      <!-- Label and input for description -->
      <div class="form-group">
        <label for="description" class="control-label">
          Description
        </label>

        <textarea id="description" name="description" placeholder="Description" class="form-control" rows="3"><%= @movie.description %></textarea>
      </div>

      <!-- Label and input for director_id -->
      <div class="form-group">
        <label for="director_id" class="control-label">
          Director
        </label>

        <%= select_tag(:director_id, options_from_collection_for_select(Director.all, :id, :name, @movie.director_id), :class => "form-control") %>
      </div>

      <button class="btn btn-success">
        Create Movie
      </button>
      or
      <a href="/movies">Cancel</a>
    </form>
  </div>
</div>

app/views/movies/show.html.erb
<div class="page-header">
  <h3>Movie #<%= @movie.id %></h3>
</div>

<div class="row">
  <div class="col-md-12 mb-2">
    <dl class="dl-horizontal">
      <dt>Title</dt>
      <dd><%= @movie.title %></dd>

      <dt>Duration</dt>
      <dd><%= @movie.duration %></dd>

      <dt>Rating</dt>
      <dd><%= @movie.rating %></dd>

      <dt>Description</dt>
      <dd><%= @movie.description %></dd>

      <dt>Director</dt>
      <dd>
        <% if @movie.director.present? %>
          <a href="/directors/<%= @movie.director_id %>">
            <%= @movie.director.name %>
          </a>
        <% end %>
      </dd>

    </dl>

    <div class="btn-group btn-group-justified">
      <a href="/movies" class="btn btn-primary">
        Back
      </a>
      <a href="/movies/<%= @movie.id %>/edit" class="btn btn-warning">
        Edit
      </a>
      <a href="/delete_movie/<%= @movie.id %>" class="btn btn-danger" rel="nofollow">
        Delete
      </a>
    </div>
  </div>
</div>